replicaCount: 2

image:
  repository: yossizxc/weather
  tag: 11
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443
  containerPort: 5000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

secret:
  secretName: tls-secret
  secretsManagerObjectName: tls-secret