apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weather-app-deployment
  labels:
    app: {{ .Release.Name }}-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-weather-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-weather-app
    spec:
      containers:
        - name: weather-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}

          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}