apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-aws-tls-secret
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Values.secret.secretName }}
      type: kubernetes.io/tls
      data:
        - objectName: tls.crt
          key: tls.crt
        - objectName: tls.key
          key: tls.key
  parameters:
    objects: |
      - objectName: "{{ .Values.secret.secretsManagerObjectName }}"
        objectType: "secretsmanager"
