apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-tls-secret
  namespace: weather
spec:
  provider: aws
  secretObjects:
    - secretName: tls-secret
      type: kubernetes.io/tls
      data:
        - objectName: tls.crt
          key: tls.crt
        - objectName: tls.key
          key: tls.key
  parameters:
    objects: |
      - objectName: "tls-secret"
        objectType: "secretsmanager"