apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weather-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-weather-app